import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const monserratFont = localFont({
  src: "./fonts/MonserratFont.ttf",
  variable: "--font-monserrat",
  weight: "400 500 600 700",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monserratFont.variable}>
        {children}
      </body>
    </html>
  );
}
